#!/usr/bin/env bash
# Regenerates deploy/frontend/cloudflare-realip.conf from Cloudflare's published ranges
# (https://www.cloudflare.com/ips). Review the diff, then restart the frontend: Nginx reads the file at start.
set -euo pipefail
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/cloudflare-realip.conf"
v4="$(curl -sf https://www.cloudflare.com/ips-v4)"; v6="$(curl -sf https://www.cloudflare.com/ips-v6)"
[ -n "$v4" ] && [ -n "$v6" ] || { echo "could not download the Cloudflare ranges" >&2; exit 1; }
{
  echo "# Generated by deploy/frontend/update-cloudflare-ips.sh from https://www.cloudflare.com/ips on $(date -u +%F)."
  echo "# Behind Cloudflare, the TCP peer is a Cloudflare edge address; the real client is in CF-Connecting-IP."
  echo "# The header is honored only when the peer is one of these ranges, so a direct caller cannot forge it."
  echo "# The restored address becomes \$remote_addr: it feeds the proxy's first limiting layer and the"
  echo "# X-Forwarded-For sent to auth-api (which trusts only this frontend's fixed address)."
  while read -r range; do echo "set_real_ip_from $range;"; done <<<"$v4"
  while read -r range; do echo "set_real_ip_from $range;"; done <<<"$v6"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive off;"
} > "$OUT"
echo "updated $OUT"
